services:
  # Base de datos PostgreSQL compartida
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s  # Reducido de 30s
      timeout: 5s    # Reducido de 10s
      retries: 5
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M
    command: >
      postgres 
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  # Redis para caché optimizado
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 300
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

  # NIT Validation Service
  nit-validation-service:
    build: 
      context: ./nit-validation-service
      dockerfile: Dockerfile
    container_name: nit-validation-service
    environment:
      POSTGRES_DB: ${NIT_DB_NAME}
      POSTGRES_USER: ${NIT_DB_USER}
      POSTGRES_PASSWORD: ${NIT_DB_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # Permite override completo si se desea
      DATABASE_URL: ${NIT_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_TTL: ${REDIS_TTL}
    ports:
      - "${NIT_SERVICE_PORT}:8002"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./nit-validation-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service optimizado
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DATABASE_URL: ${USER_DATABASE_URL}
      REDIS_URL: "redis://redis-cache:6379"
    ports:
      - "${USER_SERVICE_PORT}:8001"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      nit-validation-service:
        condition: service_healthy
      audit-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./user-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s  # Reducido de 30s
      timeout: 5s    # Reducido de 10s
      retries: 3
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Audit Service
  audit-service:
    build: 
      context: ./audit-service
      dockerfile: Dockerfile
    container_name: audit-service
    environment:
      DATABASE_URL: ${AUDIT_DATABASE_URL}
    ports:
      - "${AUDIT_SERVICE_PORT}:8003"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./audit-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auth Service
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      DATABASE_URL: ${USER_DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES}
    ports:
      - "${AUTH_SERVICE_PORT}:8004"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./auth-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Proveedor Service
  proveedor-service:
    build: 
      context: ./proveedor-service
      dockerfile: Dockerfile
    container_name: proveedor-service
    environment:
      DATABASE_URL: ${PROVEEDOR_DATABASE_URL}
      REDIS_URL: "redis://redis-cache:6379"
    ports:
      - "${PROVEEDOR_SERVICE_PORT}:8006"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./proveedor-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Product Service (HU-WEB-003) - Carga individual de productos
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      # --- Base de datos (como en tus otros servicios) ---
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # Permite override completo si se desea (toma prioridad)
      DATABASE_URL: ${PRODUCT_DATABASE_URL}

      # --- Pool / tuning opcional (iguales a tu estilo optimizado) ---
      DB_POOL_SIZE: "20"
      DB_MAX_OVERFLOW: "40"
      DB_POOL_RECYCLE: "1800"
      DB_POOL_TIMEOUT: "30"
      DB_CONNECT_TIMEOUT: "10"
      SQL_ECHO: "false"

    ports:
      - "${PRODUCT_SERVICE_PORT}:8005"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./product-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M


  # Pedidos Service (HU-WEB-004)
  pedidos-service:
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile
    container_name: pedidos-service
    environment:
      # --- Base de datos ---
      PEDIDOS_DB_NAME: ${PEDIDOS_DB_NAME}
      PEDIDOS_DB_USER: ${PEDIDOS_DB_USER}
      PEDIDOS_DB_PASSWORD: ${PEDIDOS_DB_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # Permite override completo si se desea
      PEDIDOS_DATABASE_URL: ${PEDIDOS_DATABASE_URL}
      
      # --- URLs de servicios ---
      PRODUCT_SERVICE_URL: "http://product-service:8005"
      
      # --- Pool / tuning ---
      DB_POOL_SIZE: "20"
      DB_MAX_OVERFLOW: "40"
      DB_POOL_RECYCLE: "1800"
      DB_POOL_TIMEOUT: "30"
      DB_CONNECT_TIMEOUT: "10"
      SQL_ECHO: "false"
    
    ports:
      - "${PEDIDOS_SERVICE_PORT}:8007"
    depends_on:
      postgres-db:
        condition: service_healthy
      product-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./pedidos-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Optimizaciones de recursos
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
  
  # Ingestion Service (carga masiva)
  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: ingestion-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_VERIFY_URL: "http://auth-service:8004/verify-token"
      SKIP_AUTH: "${SKIP_AUTH}"
    ports:
      - "${INGESTION_SERVICE_PORT}:8010"
    depends_on:
      postgres-db:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./ingestion-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Validator Service (validación de staging)
  validator-service:
    build:
      context: ./validator-service
      dockerfile: Dockerfile
    container_name: validator-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_VERIFY_URL: "http://auth-service:8004/verify-token"
      SKIP_AUTH: "${SKIP_AUTH}"
    ports:
      - "${VALIDATOR_SERVICE_PORT}:8011"
    depends_on:
      postgres-db:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./validator-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Upserter Service (pasa de staging a final)
  upserter-service:
    build:
      context: ./upserter-service
      dockerfile: Dockerfile
    container_name: upserter-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_VERIFY_URL: "http://auth-service:8004/verify-token"
      SKIP_AUTH: "${SKIP_AUTH}"
    ports:
      - "${UPSERTER_SERVICE_PORT}:8012"
    depends_on:
      postgres-db:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - ./upserter-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # API Gateway (Nginx) - Opcional
  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - nit-validation-service
      - audit-service
      - auth-service
      - proveedor-service
      - pedidos-service
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
    name: microservices-network

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data

